### ISSUE TITLE
Install on mac broken since 3.2.3

### ISSUE THREAD

**Issue by danez** [tonyganch/gonzales-pe#149]
```
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/user/.nvm/versions/node/v4.2.6/bin/node" "/Users/user/.nvm/versions/node/v4.2.6/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.7.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! gonzales-pe@3.2.5 postinstall: `./scripts/postinstall.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the gonzales-pe@3.2.5 postinstall script './scripts/postinstall.sh'.
```

**Comment by danez** [comment]
It might be that the check for 'lib' is wrong, I'm not sure what the cwd is when calling the script.

**Comment by bgriffith** [comment]
Same problem - any version greater than `3.2.2` won't install via npm (but does install/build using github repo url)

**Comment by tonyganch** [comment]
Hold on, working on it

**Comment by tonyganch** [comment]
Done. Please try with `@3.2.6`.

**Comment by logiclabs** [comment]
This fix appears to have broken Windows compatibility.  "-e was unexpected at this time."

`if [ -e ./scripts/postinstall.sh ]; then ./scripts/postinstall.sh; fi`

**Comment by stukennedy** [comment]
yeah, broken on windows ... this is a bash-specific script you've got here.

**Comment by DanPurdy** [comment]
Hi @tonyganch sorry to ask again but these scripts are preventing any install on windows currently (being bash specific) and blocking us releasing our update to use 3.2.6 :cry:  Is there any chance you could just remove these scripts again for now and roll a quick patch release? Thanks!

Also appveyor have some good support for testing on windows machines https://www.appveyor.com/ and are free for open source projects if you're looking to avoid issues with windows in the future (without having to touch one of those PC's!).

**Comment by clcpolevaulter** [comment]
@tonyganch thoughts on @DanPurdy's request? We'd love to have his changes for another issue on scss-lint.

**Comment by mven** [comment]
@DanPurdy @tonyganch I just tested on my Windows installation using the manual build instructions (3) in the readme, as well as modifying the `package.json` and I was able to successfully `npm install` the dev branch (3.2.6). Here's my modifications to the `package.json`. I know it's ugly, but I had to prepend `bash` to the script calls or Windows would not recognize the `.` or it would complain about `-e` flag etc (I've changed to `-f` since it wasn't giving me problems).

``` bash
  "scripts": {
    "autofix-tests": "bash ./scripts/build.sh && bash ./scripts/autofix-tests.sh",
    "build": "bash ./scripts/build.sh",
    "init": "bash ./scripts/init.sh",
    "log": "bash ./scripts/log.sh",
    "prepublish": "bash ./scripts/prepublish.sh",
    "postinstall": "[ ! -f ./scripts/postinstall.sh ] || bash ./scripts/postinstall.sh",
    "postpublish": "bash ./scripts/postpublish.sh",
    "test": "bash ./scripts/build.sh && bash ./scripts/test.sh"
  },
```

**Comment by mven** [comment]
^ I used Git Bash terminal for this.

**Comment by DanPurdy** [comment]
@mven yeah that would be fine but it's not a workable solution for this. The issue is these scripts aren't even necessary when just using the package as a dependency  from npm and unless you take some manual steps that 99.9% of windows users or indeed anyone not using a bash shell won't then it fails to install and causes npm to throw, which means we will be inundated with broken install issues if we were to push our release out.

**Comment by mven** [comment]
@DanPurdy After posting, I thought this might be the case wherein the dev would be forced to use bash, which might not be for all Windows users. It makes sense with your explanation.

**Comment by colin-marshall** [comment]
@DanPurdy is this fixed now so you don't have to use a fork anymore?

**Comment by DanPurdy** [comment]
@colin-marshall this is true but currently the fork doesn't really differ from the base repo here so we wont really need to change it until we update the base repo. @tonyganch was kind enough to give both @bgriffith and I write access to this repo too so we can hopefully help out merging PR's and also working directly on the AST itself, which we intend to do when we have time.
