### ISSUE TITLE
Wrong parsing of @media inside @media

### ISSUE THREAD

**Issue by maletsden** [tonyganch/gonzales-pe#289]
If we have @media inside the @media:

```
@media screen
	@media print
   		h1
   			color: black
	h2
   		color: blue
```

Then Gonzales determine «h2» as separate rule (not the child of @media screen)

But this word fine:

```
@media screen
	h2
   		color: blue
	@media print
   		h1
   			color: black

```

Could this be solved?

**Comment by AleshaOleg** [comment]
@maletsden What do you suppose to see as a result of converting your Sass example to CSS?

**Comment by maletsden** [comment]
I don’t need to parse SASS to CSS.

@media screen
	@media print
   		h1
   			color: black
	h2
   		color: blue

I just want «@media print»  to be a child (atrule inside «@media screen».content) of «@media screen»

Is it posible?

**Comment by maletsden** [comment]
And «h2» should be inside «@media screen» as well

Thanks

**Comment by AleshaOleg** [comment]
I think that impossible usage. Because in CSS we can just use `@media print.` If you wanna to extend your `screen` simply use `@media screen, print` - like in examples on [this](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) page, outside of other `@media.` For example:

```
@media screen, print
    h2
   	color: blue
  
@media screen
    h3
	color: red
  
@media print
    h1
	color: black
```

That's why asked about CSS, how you suppose your compiled variant should look?
`@media screen @media print.`? It's obviously wrong.

**Comment by maletsden** [comment]
Okay, probably, you are right. Sorry, for your time

Thank you a lot

**Comment by maletsden** [comment]
Also, have you worked on nested properties? Something like that:

.funky
	:font 20px/24px fantasy
		weight: bold
