### ISSUE TITLE
Parser failure with empty input

### ISSUE THREAD

**Issue by gmac** [tonyganch/gonzales-pe#71]
I read an empty input file (contains zero characters), and parse the contents. Results:

```
/Users/greg/Projects/presto/node_modules/gonzales-pe/lib/parse.js:18
        throw new Error('Please, pass a string to parse');
```

I think it would make more sense for the parser to pass-through empty contents rather than erring. Otherwise, all input must be prepended with a `//\n` (empty line comment) for safe parsing.

**Comment by tonyganch** [comment]
I’m not sure about this one.
I think returning an empty space is technically wrong, because you can’t parse nothing (an empty string) as something that actually isn’t there (a space node). That’s a lie, you know :elephant:
I think js api should work with non-empty strings only and if some tool works with file content, it should handle empty content in a way that’s more suitable for this tool. For example, not call parser for such files at all.

**Comment by gmac** [comment]
Given that compilers allow empty files to be parsed (into empty strings), I'd expect a lexical analysis tool to match this behavior. I agree that returning a `space` node may not be the most appropriate node type, but those are semantics. The primary objective here is to return a valid AST Node for any input that would be valid for a compiler – otherwise, it feels odd that we can blindly read files into a compiler, but not into an equivocal parser.

**Comment by gmac** [comment]
Oh – duh. The obvious answer: what if this circumstance yields an empty `stylesheet` node? That would be a sensible result... when I submit an empty stylesheet string, I get back a `stylesheet` node with zero children.

**Comment by gmac** [comment]
Pull request updated: empty string yields empty stylesheet node.

**Comment by tonyganch** [comment]
That sounds ok :)

**Comment by gmac** [comment]
PR went through, thanks! Excited to see this maturing into a stable and robust tool.
