### ISSUE TITLE
Roll a Release

### ISSUE THREAD

**Issue by Snugug** [tonyganch/gonzales-pe#94]
Hey Tony!

We've got some items that are blocked on some things that we've talked about are fixed in `dev`. Is there an ETA for a new release?

**Comment by tonyganch** [comment]
Hey!
I'm very sorry to keep you waiting. I'll be back in a week and finish docs. That's all that left for the release.
:elephant:

**Comment by Snugug** [comment]
Great, thank you!

**Comment by tonyganch** [comment]
@Snugug, just a little update on the issue.
I've published `gonzales-pe@3.0.0-beta`.
Though it lacks documentation on parse tree, it contains all the breaking changes.
It means that other issues will be closed as patches and they will be backwards compatible.

I'm in the process of writing docs, once they are ready, I'll roll a stable `@3.0.0`.
If you notice anything awful by that time (or have any questions), please let me know.
Previous tests are passing but I don't really trust them.

Thank you for your endless patience and periodic pings.

**Comment by Snugug** [comment]
Awesome, thank you! I'll take a look and see what happens to Sass Lint.

Thank you so much for your work!

**Comment by tonyganch** [comment]
So, I've moved csscomb project to new gonzales version and have found no bugs in api so far.
I've also added docs for node types, so I'm planning to release a stable 3.0 version later today.
All parsing bugs will be then fixed and released as patches, so I assume it will make our work faster.

**Important changes in api after 3.0 beta release!**
(1) `node.remove()` renamed to `node.removeChild()` (because I have future plans to implement `node.remove()` that will remove the node itself).
(2) `node.removeChild()` now returns a removed node.
(3) `traverseBy...` methods are now available in all nodes (not only root ones).
(4) `get()`, `first()` and `last()` now return child nodes or `null` if no child node is found. So this code will now fail, for example:

``` js
// Assume that node's type is `space` or `ident`, something that has content of string type.
node.first().is('delimiter'); // Will throw "Uncaught TypeError: Cannot read property 'is' of null"
```

(5) `node.length` now returns number of child nodes. For example:

``` js
// Again, assume that node's type is `space`.
node.length; // Will return 0.
```

(6) Callback for all `node.traverse...` methods now get 4 parameters (previously it was one object). The forth parameter is `nestingLevel` which can be super useful for blocks in scss. Please refer to docs: https://github.com/tonyganch/gonzales-pe#parsetreetraversecallback

@benthemonkey, @bgriffith, @cgtm, @jantimon, @shellscape, @Snugug,
I want to thank you all for being so awesome and for all your hard work while testing.
Thank you so much!
I hope that remaining bugs will be fixed pretty quickly :)

**Comment by bgriffith** [comment]
No problem @tonyganch - glad to help!

**Comment by shellscape** [comment]
:+1:
